# Generated by Django 4.2.9 on 2024-01-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=10, unique=True)),
                ("url", models.URLField()),
                ("visits", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
